if (PICO_RP2040)
  add_definitions(-DPICO_RP2040)
  set(PICO_PLATFORM_DIR rp2040)
endif()

if (PICO_RP2350)
  add_definitions(-DPICO_RP2350)
  set(PICO_PLATFORM_DIR rp2350)
endif()

include_directories(
  ${CMAKE_SOURCE_DIR}/src
  ${CMAKE_SOURCE_DIR}/src/demos/res/assets/default/inc
  ${CMAKE_SOURCE_DIR}/src/awtk-port
  ${CMAKE_SOURCE_DIR}/src/board/lcd
  ${CMAKE_SOURCE_DIR}/src/board/fatfs
  ${CMAKE_SOURCE_DIR}/src/board/sdcard
  ${CMAKE_SOURCE_DIR}/src/board/font
  ${CMAKE_SOURCE_DIR}/src/board/config
  ${CMAKE_BINARY_DIR}/generated/pico_base
  ${PICO_SDK_PATH}/src/common/pico_binary_info/include
  ${PICO_SDK_PATH}/src/common/boot_picoboot_headers/include
  ${PICO_SDK_PATH}/src/common/pico_util/include
  ${PICO_SDK_PATH}/src/common/boot_picobin_headers/include
  ${PICO_SDK_PATH}/src/common/pico_stdlib_headers/include
  ${PICO_SDK_PATH}/src/common/hardware_claim/include
  ${PICO_SDK_PATH}/src/common/pico_time/include
  ${PICO_SDK_PATH}/src/common/pico_bit_ops_headers/include
  ${PICO_SDK_PATH}/src/common/pico_usb_reset_interface_headers/include
  ${PICO_SDK_PATH}/src/common/pico_base_headers/include
  ${PICO_SDK_PATH}/src/common/pico_sync/include
  ${PICO_SDK_PATH}/src/common/pico_divider_headers/include
  ${PICO_SDK_PATH}/src/common/boot_uf2_headers/include
  ${PICO_SDK_PATH}/src/boards/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_exception/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_powman/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_malloc/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_multicore/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_i2c/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_riscv_platform_timer/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_sync/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_irq/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_gpio/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_interp/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_bootrom/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_uart/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_timer/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_base/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_rcp/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_pio/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_btstack/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_pll/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_stdio_rtt/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_stdio_semihosting/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_clocks/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_lwip/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_ticks/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_platform_sections/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_xip_cache/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_aon_timer/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_fix/rp2040_usb_device_enumeration/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_sha256/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_cyw43_arch/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_boot_lock/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_dcp/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_double/include
  ${PICO_SDK_PATH}/src/rp2_common/cmsis/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_unique_id/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_pwm/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_platform_panic/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_vreg/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_dma/include
  ${PICO_SDK_PATH}/src/rp2_common/boot_bootrom_headers/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_sync_spin_lock/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_platform_compiler/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_i2c_slave/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_printf/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_int64_ops/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_runtime_init/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_stdio_uart/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_riscv/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_atomic/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_time_adapter/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_mem_ops/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_hazard3/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_resets/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_cyw43_driver/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_clib_interface/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_float/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_sha256/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_adc/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_watchdog/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_rand/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_runtime/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_spi/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_divider/include
  ${PICO_SDK_PATH}/src/rp2_common/tinyusb/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_mbedtls/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_rtc/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_stdio/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_xosc/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_async_context/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_flash/include
  ${PICO_SDK_PATH}/src/rp2_common/hardware_flash/include
  ${PICO_SDK_PATH}/src/rp2_common/pico_stdio_usb/include
  ${PICO_SDK_PATH}/src/${PICO_PLATFORM_DIR}/boot_stage2/include
  ${PICO_SDK_PATH}/src/${PICO_PLATFORM_DIR}/hardware_regs/include
  ${PICO_SDK_PATH}/src/${PICO_PLATFORM_DIR}/hardware_structs/include
  ${PICO_SDK_PATH}/src/${PICO_PLATFORM_DIR}/pico_platform/include
)
